### ISSUE TITLE
Having some issues

### ISSUE THREAD

**Issue by Newcool1230** [Andrews54757/Anti-Anti-Debug#5]
I'm having a hard time getting the extension to work properly on https://parcelsapp.com

I'm on firefox, opened devtool on a new tab, disabled source maps, gave the extension permission, loaded the site. My CPU and RAM sky rockets. Am I missing anything?

**Comment by Andrews54757** [comment]
I was able to reproduce, seems like they are using a new detection strategy? Will investigate further.

**Comment by Andrews54757** [comment]
It seems to only happen on Firefox

**Comment by Andrews54757** [comment]
Fixed in 1.0.5
