### ISSUE TITLE
issue: can't use twitch.tv while the plugin is on. and a question.

### ISSUE THREAD

**Issue by Id-ware** [Andrews54757/Anti-Anti-Debug#7]
EDIT: 
-
i downloaded the repo and loaded that as an unpacked plugin (instead of the plugin i had downloaded originally from the chrome store, before it was taken down) and now twitch.tv seems to work fine. so most of the message i originally posted here is irrlevent, tho some of it still may be relevant (like adding a whitelist feature, and why was the plugin taken down) so i will keep the original message below for those who interested..

original message:
-
hi,
i've been using this plugin and it's been very helpful to me so far.

but, i've noticed an issue: when accessing twitch while the plugin is enabled, you wont be able to use twitch.tv properly (like following a channel, checking notifications, ect)
i think they have some kind of a way to try to detect this plugin and block usage of their website while this plugin is enabled.

it gave me an idea, can you add something like a website whitelist so you can disable this plugin on websites you don't want it to work in? (as a simple and quick fix for now)

also, i noticed (in a big delay tho) that the plugin is no longer in the chrome addons store, is the development for this plugin ended?
and if so, what other plugin do you recommend to use?

thanks

**Comment by Andrews54757** [comment]
Are you sure that the "plugin" you are talking about is Anti-Anti-Debug? It has never been taken down from the web store.
https://chromewebstore.google.com/detail/anti-anti-debug/mnmnmcmdkigakhlfkcdimghndnmomfeo
