### ISSUE TITLE
https://icelz.newsrade.com/ Doesn't work

### ISSUE THREAD

**Issue by Timbo303** [Andrews54757/Anti-Anti-Debug#8]
It just shows the funny gif regardless of addon enabled or not which is their anti debugger.
![Screenshot 2024-02-11 112759](https://github.com/Andrews54757/Anti-Anti-Debug/assets/28489517/5fcfb202-0053-4dcb-8573-3f2386227f45)

**Comment by Andrews54757** [comment]
It works for me. Make sure you gave it permission to access the site. Also check the troubleshooting steps.
